{{- if and (not .Values.internal.existingSecret) .Values.internal.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-internal" (include "relate-mail.fullname" .) }}
  labels:
    {{- include "relate-mail.labels" . | nindent 4 }}
type: Opaque
stringData:
  internalApiKey: {{ .Values.internal.apiKey | quote }}
{{- end }}
