{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "relate-mail.fullname" .) }}
  labels:
    {{- include "relate-mail.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: {{ include "relate-mail.dbConnectionString" . | quote }}
{{- end }}
