{{- if and (not .Values.outbound.existingSecret) .Values.outbound.relayPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-outbound" (include "relate-mail.fullname" .) }}
  labels:
    {{- include "relate-mail.labels" . | nindent 4 }}
type: Opaque
stringData:
  relayPassword: {{ .Values.outbound.relayPassword | quote }}
{{- end }}
